name: examo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  flutter_riverpod: ^2.5.1
  line_awesome_flutter: ^2.0.0
  phosphor_flutter: ^2.1.0
  font_awesome_flutter: ^10.6.0
  shared_preferences: ^2.5.3
  dio: ^5.8.0+1
  flutter_tabler_icons: ^1.43.0
  change_app_package_name: ^1.5.0
  google_fonts: ^6.3.1
  remixicon: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/auth-image/
    - assets/images/
    - assets/sidebar-icon/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700